import { Profile, Payment, Certificate, StudentSkillAccess } from '@/types/database';

export const SAMPLE_STUDENTS: Profile[] = [
  {
    id: 'std-1',
    full_name: 'Aarav Patel',
    email: 'aarav.patel@college.edu',
    phone: '+91 98765 43210',
    university: 'IIT Hyderabad',
    student_id_number: '21BCE1042',
    branch_name: 'CSE Core',
    year: 3,
    role: 'student',
    avatar_url: null,
    is_active: true,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'std-2',
    full_name: 'Priya Sharma',
    email: 'priya.sharma@tech.ac.in',
    phone: '+91 98123 45678',
    university: 'NIT Warangal',
    student_id_number: '20BCS089',
    branch_name: 'CSE AI & ML',
    year: 4,
    role: 'student',
    avatar_url: null,
    is_active: true,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'std-3',
    full_name: 'Rahul Varma',
    email: 'rahul.varma@university.edu',
    phone: '+91 97456 12389',
    university: 'BITS Pilani',
    student_id_number: '2021A7PS0042H',
    branch_name: 'CSE Cyber Security',
    year: 2,
    role: 'student',
    avatar_url: null,
    is_active: true,
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  {
    id: 'std-4',
    full_name: 'Sneha Reddy',
    email: 'sneha.reddy@iiit.ac.in',
    phone: '+91 99887 76655',
    university: 'IIIT Bangalore',
    student_id_number: 'IIITB-DS-2204',
    branch_name: 'CSE Data Science',
    year: 3,
    role: 'student',
    avatar_url: null,
    is_active: true,
    created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 12 * 86400000).toISOString(),
  },
  {
    id: 'std-5',
    full_name: 'Vikram Joshi',
    email: 'vikram.j@engineering.edu',
    phone: '+91 96543 21870',
    university: 'DTU Delhi',
    student_id_number: '2K21/CO/312',
    branch_name: 'CSE Core',
    year: 2,
    role: 'student',
    avatar_url: null,
    is_active: true,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: 'std-6',
    full_name: 'Ananya Deshmukh',
    email: 'ananya.d@coep.ac.in',
    phone: '+91 94230 87123',
    university: 'COEP Pune',
    student_id_number: '112103045',
    branch_name: 'CSE AI & ML',
    year: 4,
    role: 'student',
    avatar_url: null,
    is_active: true,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: 'std-7',
    full_name: 'Karthik Sundaram',
    email: 'karthik.s@annauniv.edu',
    phone: '+91 93456 78901',
    university: 'Anna University',
    student_id_number: '2021105088',
    branch_name: 'CSE Cyber Security',
    year: 3,
    role: 'student',
    avatar_url: null,
    is_active: false,
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: 'std-8',
    full_name: 'Meera Nair',
    email: 'meera.nair@nitc.ac.in',
    phone: '+91 91234 56780',
    university: 'NIT Calicut',
    student_id_number: 'B210455CS',
    branch_name: 'CSE Data Science',
    year: 1,
    role: 'student',
    avatar_url: null,
    is_active: true,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  }
];

export const SAMPLE_PAYMENTS = [
  {
    id: 'pay-101',
    student_id: 'std-1',
    student: { full_name: 'Aarav Patel', email: 'aarav.patel@college.edu' },
    amount: 1499,
    payment_method: 'upi',
    payment_status: 'paid',
    transaction_reference: 'UPI/2026/0928/847291',
    created_at: new Date(Date.now() - 4 * 3600000).toISOString(),
  },
  {
    id: 'pay-102',
    student_id: 'std-2',
    student: { full_name: 'Priya Sharma', email: 'priya.sharma@tech.ac.in' },
    amount: 2999,
    payment_method: 'upi',
    payment_status: 'paid',
    transaction_reference: 'UPI/2026/0927/109283',
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'pay-103',
    student_id: 'std-3',
    student: { full_name: 'Rahul Varma', email: 'rahul.varma@university.edu' },
    amount: 999,
    payment_method: 'card',
    payment_status: 'paid',
    transaction_reference: 'CRD-TXN-99412',
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'pay-104',
    student_id: 'std-4',
    student: { full_name: 'Sneha Reddy', email: 'sneha.reddy@iiit.ac.in' },
    amount: 1999,
    payment_method: 'netbanking',
    payment_status: 'paid',
    transaction_reference: 'HDFC-NB-88301',
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'pay-105',
    student_id: 'std-5',
    student: { full_name: 'Vikram Joshi', email: 'vikram.j@engineering.edu' },
    amount: 499,
    payment_method: 'upi',
    payment_status: 'paid',
    transaction_reference: 'UPI/2026/0924/774102',
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'pay-106',
    student_id: 'std-6',
    student: { full_name: 'Ananya Deshmukh', email: 'ananya.d@coep.ac.in' },
    amount: 1499,
    payment_method: 'upi',
    payment_status: 'paid',
    transaction_reference: 'UPI/2026/0922/551982',
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: 'pay-107',
    student_id: 'std-7',
    student: { full_name: 'Karthik Sundaram', email: 'karthik.s@annauniv.edu' },
    amount: 499,
    payment_method: 'upi',
    payment_status: 'pending',
    transaction_reference: 'UPI/2026/0920/331094',
    created_at: new Date(Date.now() - 9 * 86400000).toISOString(),
  },
];

export const SAMPLE_CERTIFICATES = [
  {
    id: 'cert-1',
    certificate_number: 'CF-2026-CSE-84920',
    student_id: 'std-1',
    skill_id: 'a1000000-0000-0000-0000-000000000001',
    student: { full_name: 'Aarav Patel', email: 'aarav.patel@college.edu', branch_name: 'CSE Core' },
    skill: { name: 'Data Structures & Algorithms in C++', slug: 'dsa-cpp' },
    issue_date: new Date(Date.now() - 3 * 86400000).toISOString(),
    status: 'unlocked',
    verification_url: 'https://vyat.com/verify/CF-2026-CSE-84920',
  },
  {
    id: 'cert-2',
    certificate_number: 'CF-2026-AIML-19042',
    student_id: 'std-2',
    skill_id: 'a2000000-0000-0000-0000-000000000003',
    student: { full_name: 'Priya Sharma', email: 'priya.sharma@tech.ac.in', branch_name: 'CSE AI & ML' },
    skill: { name: 'Machine Learning Fundamentals with Scikit-Learn', slug: 'ml-fundamentals' },
    issue_date: new Date(Date.now() - 6 * 86400000).toISOString(),
    status: 'unlocked',
    verification_url: 'https://vyat.com/verify/CF-2026-AIML-19042',
  },
  {
    id: 'cert-3',
    certificate_number: 'CF-2026-SEC-44102',
    student_id: 'std-3',
    skill_id: 'a4000000-0000-0000-0000-000000000001',
    student: { full_name: 'Rahul Varma', email: 'rahul.varma@university.edu', branch_name: 'CSE Cyber Security' },
    skill: { name: 'Network Security & Penetration Testing', slug: 'network-security' },
    issue_date: new Date(Date.now() - 10 * 86400000).toISOString(),
    status: 'unlocked',
    verification_url: 'https://vyat.com/verify/CF-2026-SEC-44102',
  },
  {
    id: 'cert-4',
    certificate_number: 'CF-2026-DATA-77192',
    student_id: 'std-4',
    skill_id: 'a3000000-0000-0000-0000-000000000001',
    student: { full_name: 'Sneha Reddy', email: 'sneha.reddy@iiit.ac.in', branch_name: 'CSE Data Science' },
    skill: { name: 'Exploratory Data Analysis with Pandas & Seaborn', slug: 'eda-pandas' },
    issue_date: new Date(Date.now() - 14 * 86400000).toISOString(),
    status: 'unlocked',
    verification_url: 'https://vyat.com/verify/CF-2026-DATA-77192',
  },
];
